### ISSUE TITLE
uber% with vow hard to see - would it be possible to add outline?

### ISSUE THREAD

**Issue by kopikatz** [tf2huds/zonahud#1]
hey lardox, love your hud but encountered this issue with it a bunch of times while playing 6s this season - https://cdn.discordapp.com/attachments/1003530465304653846/1098860545907634226/image.png

in the heat of the moment, it is a bit difficult to see the uber% with vow, i wonder if it would be possible to add a black outline so it can be seen much more clearer. i use m0rehud font with pink color. thank you in advance :D

**Comment by mastercoms** [comment]
lardox does not monitor this repo and generally isn't active for HUDs anymore, I would recommend asking on the [huds.tf discord](https://discord.gg/Hz3Q4Z8) for edits

**Comment by kopikatz** [comment]
ok, thank you!
